version: '3.8'
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.5'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
  kafka:
    image: 'bitnami/kafka:2.8'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,INTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,INTERNAL://kafka:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=10
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - 9092:9092
      - 9093:9093
    depends_on:
      - zookeeper
  kafdrop:
    image: obsidiandynamics/kafdrop:3.30.0
    environment:
      - KAFKA_BROKERCONNECT=kafka:9093
      - SERVER_SERVLET_CONTEXTPATH=/
    ports:
      - 9000:9000
    depends_on:
      - kafka
  jupyterlab:
    image: github.com/laiyewhon/marvel-snap:0.0.1-SNAPSHOT
    build: .
    ports:
      - 8888:8888
    volumes:
      - ${PWD}:/home/jovyan/workspace
  sink-parquet:
    image: github.com/laiyewhon/marvel-snap-sink-parquet:0.0.1-SNAPSHOT
    build: sink-parquet
    volumes:
      - ${PWD}/data:/app/data
